name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0.
        # For more details, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - name: Cache packages
        id: packages-cache
        uses: actions/cache@v2
        with:
          path: cache/
      - name: Install dependencies
        run: sudo apt-get install git build-essential -y
      - name: Install live-build
        run: |
          sudo mkdir -p /usr/srv
          cd /usr/srv
          git clone https://salsa.debian.org/live-team/live-build.git
          cd live-build
          sudo make install
      - name: Build the image
        run: |
          sudo ld config
          sudo ld build

  release:
    needs: build
    runs-on: ubuntu-lastest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create Release
      id: create_release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files:
