name: Unstable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install git build-essential -y
      - name: Install live-build
        run: |
          git clone https://salsa.debian.org/live-team/live-build.git
          cd live-build
          sudo dpkg-buildpackage -b -uc -us
          cd ..
          sudo apt-get install ./live-build*
          rm -rf live-build
      - name: Build the image
        run: |
          sudo lb config
          sudo lb build

  release:
    needs: build
    runs-on: ubuntu-lastest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create Release
      id: create_release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        prerelease: true
        title: "Development Build"
        files:
